export const homeCatalogContent = {
  eyebrow: 'Automation projects, packaged like products',
  headline: 'A catalog of workflow projects built to sell, scale, and support service businesses.',
  subheadline: 'Explore curated automation projects across content, lead generation, appointments, admin ops, AI agents, and CRM follow-up. Every project is structured like a deliverable, not a vague portfolio entry.',
  featuredCategoriesLabel: 'Browse by business outcome',
  featuredProjectsLabel: 'Featured projects',
  processLabel: 'How these projects are delivered',
  processSteps: [
    'Each project is framed around a business outcome first, not just a tool stack.',
    'Private client work is anonymized while preserving the workflow logic and deliverables.',
    'Every detail page is built to show what the project does, how it works, and what a buyer gets.',
  ],
  finalCtaTitle: 'Need one of these adapted to your workflow?',
  finalCtaBody: 'Use the catalog to find the closest-fit project, then we can adapt the stack, channels, and handoff logic to your process.',
  finalCtaPrimary: 'Browse all projects',
  finalCtaSecondary: 'Book a discovery call',
}

export const accessPageDefaults = {
  eyebrow: 'Instant access',
  guarantee: 'Digital products are delivered by email after payment, with setup notes and direct links so you can move from checkout to implementation quickly.',
  supportNote: 'Secure checkout is handled with Stripe Elements. Eligible buyers will see card, Link, and wallet options such as Google Pay directly inside the page.',
  checkoutLabel: 'Pay now',
  contactHeading: 'Buyer details',
  contactBody: 'Enter the email address where you want the workflow links and setup notes delivered.',
  paymentMethodsLabel: 'Payment methods',
  paymentMethodsBody: 'This embedded Stripe form supports cards, Link, and eligible wallets. The exact options shown depend on device and browser eligibility.',
  summaryLabel: 'Order summary',
  deliveryLabel: 'Delivery',
  deliveryBody: 'After payment, Stripe confirms the purchase and the workflow link is emailed to the buyer through our n8n fulfillment flow.',
  buyerEmailLabel: 'Email address',
  buyerEmailPlaceholder: 'you@example.com',
  buyerEmailHelp: 'We will send the workflow links, setup notes, and bonus materials to this address after payment.',
  checkoutErrorFallback: 'We could not load or confirm the secure payment form right now. Please try again in a moment.',
}

export const platformBundleOffers = {
  'n8n': {
    title: 'Get the full n8n workflow library',
    summary: 'Unlock the full n8n project set instead of purchasing single workflows one at a time.',
    priceLabel: '$497 bundle',
    originalPriceLabel: '$697 value',
    ctaLabel: 'Unlock all n8n projects',
    paymentLink: 'https://buy.stripe.com/test_00g000000000000000',
    stripePriceId: 'price_n8nProjectLibrary_test',
    productCode: 'bundle-n8n-project-library',
    bullets: [
      'All published n8n projects in the catalog',
      'Future n8n additions added to your library',
      'Better value than buying single workflows separately',
    ],
  },
  'claude-worker': {
    title: 'Get the full Claude worker library',
    summary: 'Bundle your agent workflows, prompt systems, and automation workers into one access path.',
    priceLabel: '$397 bundle',
    originalPriceLabel: '$557 value',
    ctaLabel: 'Unlock all Claude worker projects',
    paymentLink: 'https://buy.stripe.com/test_00g000000000000000',
    stripePriceId: 'price_claudeWorkerLibrary_test',
    productCode: 'bundle-claude-worker-library',
    bullets: [
      'All Claude worker projects in one purchase',
      'Shared prompt and handoff patterns included',
      'Useful when you want a reusable AI operations stack',
    ],
  },
  'ghl': {
    title: 'Get the full GoHighLevel project pack',
    summary: 'Access the GHL projects together so your intake, follow-up, reminders, and handoff logic stay consistent.',
    priceLabel: '$447 bundle',
    originalPriceLabel: '$636 value',
    ctaLabel: 'Unlock all GHL projects',
    paymentLink: 'https://buy.stripe.com/test_00g000000000000000',
    stripePriceId: 'price_ghlProjectPack_test',
    productCode: 'bundle-ghl-project-pack',
    bullets: [
      'All current GHL projects in the catalog',
      'A faster path to a full CRM operating layer',
      'Ideal for agencies and service businesses standardizing GHL',
    ],
  },
  'zapier': {
    title: 'Get the full Zapier project pack',
    summary: 'Combine lightweight app automations into one library for fast deployment across teams.',
    priceLabel: '$347 bundle',
    originalPriceLabel: '$497 value',
    ctaLabel: 'Unlock all Zapier projects',
    paymentLink: 'https://buy.stripe.com/test_00g000000000000000',
    stripePriceId: 'price_zapierProjectPack_test',
    productCode: 'bundle-zapier-project-pack',
    bullets: [
      'All current Zapier-based catalog projects',
      'Quick-win automations for marketing and operations',
      'A simple way to standardize smaller integrations',
    ],
  },
  'make': {
    title: 'Get the full Make scenario pack',
    summary: 'Buy the complete Make catalog when you need more complex orchestration across tools and customer ops.',
    priceLabel: '$397 bundle',
    originalPriceLabel: '$557 value',
    ctaLabel: 'Unlock all Make projects',
    paymentLink: 'https://buy.stripe.com/test_00g000000000000000',
    stripePriceId: 'price_makeScenarioPack_test',
    productCode: 'bundle-make-scenario-pack',
    bullets: [
      'All Make-powered projects in one place',
      'A stronger fit for multi-step orchestration work',
      'Useful if you want a library of reusable scenarios',
    ],
  },
  'full-stack': {
    title: 'Get the full product build pack',
    summary: 'Bundle web app and automation-backed product builds together for a more complete delivery stack.',
    priceLabel: '$697 bundle',
    originalPriceLabel: '$997 value',
    ctaLabel: 'Unlock all full-stack projects',
    paymentLink: 'https://buy.stripe.com/test_00g000000000000000',
    stripePriceId: 'price_fullStackBuildPack_test',
    productCode: 'bundle-full-stack-build-pack',
    bullets: [
      'All full-stack product projects in the catalog',
      'Best when you need UI, logic, and delivery together',
      'A stronger path than piecing together isolated builds',
    ],
  },
  'mobile': {
    title: 'Get the full mobile project pack',
    summary: 'Bundle mobile delivery patterns and related automation-backed mobile projects into one access path.',
    priceLabel: '$547 bundle',
    originalPriceLabel: '$747 value',
    ctaLabel: 'Unlock all mobile projects',
    paymentLink: 'https://buy.stripe.com/test_00g000000000000000',
    stripePriceId: 'price_mobileProjectPack_test',
    productCode: 'bundle-mobile-project-pack',
    bullets: [
      'All mobile projects in one bundle',
      'Useful for teams building cross-platform client experiences',
      'Pairs well with full-stack and CRM workflows',
    ],
  },
} as const
